export const epicWin = [
  "                  .?NMMMMMMMMMMMMMMMMMMO:                   ",
  "               .8MMMMMM8$7IIIIIIID$ZDMMMMMM?                ",
  "         ..:+ZNMMM87IIIIIIIIIIIIID$7I7II$NMMMM~             ",
  "      .$OOOOOOON88O7IIIIIIIIIIIIID$7IIIIIII$MMMM?           ",
  "    ,OOOO88OOOO8OOOO8$IIIIIIIIIIID78IIIIIIIIIINMMM~.        ",
  "   ZOOOOOMMMMMMMN8OO8O8IIIIIIIIIIDNNNNNNNN888888NMMN        ",
  "  OOOO8MMMMMMMMMMMM8OOO8IIIIIIIIIDI??????????????IMMM:.     ",
  " ZOOOMMMNDDDDDDDDMMMMOOO8IIIIIIIODI???????????????+MMM+     ",
  "+8OOMMMDDDDDDDDDDDDMMMOOO8NNNNNNNMI+?ONNDZ??????????8MMI    ",
  "OO8DMMDDDDDDDDDDDDDDMM8ODODM?????+NMM8I?$DMMO+???????OMM?   ",
  "OOOMMDDDDDDDDDDDDDDDNMMOO8$M????IMM, .  .NMMMM+???????DMM,  ",
  "O8OMMDDDDDDDDDDDDDDDDMMOOOZM???OM7      ZMMMMMM???????+MMM  ",
  "OOOMMDDDDDDDDDDDDDDDDMMOOOZM???MD       ~MMMMMMM+??????IMM? ",
  "OOOMMNDDDDDDDDDDDDDDMMNOD87M??8M.        .ID$.?MI??????+8MM.",
  "OOO8MMDDDDDDDDDDDDDNMMOOOOIM??MM.             ,MZ????????MM?",
  "MOOODMMNDDDDDDDDDDMMMDOO87IM?+NM.             ,M$???????+MMN",
  "MMOOO8MMMMDDDDDNMMMM8O8O$IIM??ZM=~~~~~~~~~~~~~ZM?????????8MM",
  "MMI8O8ONMMMMMMMMMMDOOOOZIIIM??+MMMMMMMMMMMMMMMMN+????????ZMM",
  "MMII8OOOOODNMMNDOODOO8I7IIIM?????????????????????????????IMM",
  "MMII7IO8O8OOOO888O8O7IIIIIIM?????????????????????????????IMM",
  "MMIIIIIII$OO88OOZ7IIIIIIIIIM+?+?+?+++??+++?++++??????????ZMM",
  "MM7IIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM??????????DMM",
  "MM8III7IIMNZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZMD+???????+MMN",
  "NMMIIIIIIMMZOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOZMM+????????MM?",
  "?MM7IIIIIZM8OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONM+??????+8MM.",
  " MMMIIIIIIMMZOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM+??????IMM+ ",
  " =MMZIIIII$MNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOZMM+?????+MMM  ",
  "  7MM$IIIIIOM8OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODM7??????DMM.  ",
  "   NMM7IIIIINM8OOOOOOOOOOOOOOI:,,,,,=OOOOOOOOMD??????OMM?   ",
  "    MMM7IIIIINM8OOOOOOOOOOO,::::::::::,IOOO8MN+?????DMM?    ",
  "    .DMM8IIIIIZMMZOOOOOOO::::::::::::::,,ZMM8?????+MMM=.    ",
  "      ZMMMI7I777MM8OOOOO~:::::::::::::::NMM+?????IMMM:      ",
  "       ~MMMOIIIIIOMM8ZO$,:::::::::::,IMMMI?????+NMMN        ",
  "         $MMMOIII7IMMMMD+:,,,,,,~7MMMMO+?????+NMMM:         ",
  "          .8MMMNIIZM++?OMMMMMMMMMNZ?+?????+7MMMM+           ",
  "             OMMMM8N+??????++++????????+7NMMMM~             ",
  "              ..8MMMMMM87?+++++++?I$DMMMMMM+.               ",
  "                   +8MMMMMMMMMMMMMMMMMMZ:                   ",
  "                       .,+7ZOOOZ$?~..                       ",
];
export const wins = [
  "+---------------------------------------------------+",
  "| #     #                     #     #  ###  #     # |",
  "|  #   #    ####   #    #     #  #  #   #   ##    # |",
  "|   # #    #    #  #    #     #  #  #   #   # #   # |",
  "|    #     #    #  #    #     #  #  #   #   #  #  # |",
  "|    #     #    #  #    #     #  #  #   #   #   # # |",
  "|    #     #    #  #    #     #  #  #   #   #    ## |",
  "|    #      ####    ####       ## ##   ###  #     # |",
  "+---------------------------------------------------+",
];
export const loses = [
  "+-----------------------------------------------------------+",
  "| #     #                    ######   ###  #######  ######  |",
  "|  #   #    ####   #    #    #     #   #   #        #     # |",
  "|   # #    #    #  #    #    #     #   #   #        #     # |",
  "|    #     #    #  #    #    #     #   #   #####    #     # |",
  "|    #     #    #  #    #    #     #   #   #        #     # |",
  "|    #     #    #  #    #    #     #   #   #        #     # |",
  "|    #      ####    ####     ######   ###  #######  ######  |",
  "+-----------------------------------------------------------+",
];
export const pauses = [
  "+------------------------------------------------------+",
  "| ######      #     #     #   #####   #######  ######  |",
  "| #     #    # #    #     #  #     #  #        #     # |",
  "| #     #   #   #   #     #  #        #        #     # |",
  "| ######   #     #  #     #   #####   #####    #     # |",
  "| #        #######  #     #        #  #        #     # |",
  "| #        #     #  #     #  #     #  #        #     # |",
  "| #        #     #   #####    #####   #######  ######  |",
  "+------------------------------------------------------+",
];
